dendrite:
  global:
    server_name: brc1li.duckdns.org
    disable_federation: true
  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 32m
        hajimari.io/enable: 'false'
      ingressClassName: nginx
      hosts:
      - host: dendrite.innersphere.xyz
        paths:
          - path: /
            pathType: Prefix
      tls:
        - secretName: dendrite-tls-certificate
          hosts:
            - dendrite.innersphere.xyz
